// API-Football CDN: https://media.api-sports.io/football/...
// All logos load over HTTPS — fallback to initials badge if image 404s.

const CDN = "https://media.api-sports.io/football";

const league = (id: number) => `${CDN}/leagues/${id}.png`;
const team   = (id: number) => `${CDN}/teams/${id}.png`;

/* ── Competition logos ───────────────────────────────────── */
export const LEAGUE_LOGOS: Record<string, string> = {
  // UEFA
  "Premier League":              league(39),
  "La Liga":                     league(140),
  "Serie A":                     league(135),
  "Bundesliga":                  league(78),
  "Ligue 1":                     league(61),
  "Championship":                league(40),
  "Champions League":            league(2),
  "Europa League":               league(3),
  "UEFA Champions League":       league(2),
  "UEFA Europa League":          league(3),
  "Europa Conference League":    league(848),

  // Internationals
  "World Cup":                   league(1),
  "FIFA World Cup":              league(1),
  "U20 World Cup":               league(16),
  "U17 World Cup":               league(19),
  "AFCON":                       league(6),
  "Africa Cup of Nations":       league(6),

  // African club
  "CAF Champions League":        league(20),
  "CAF Confederation Cup":       league(21),

  // African domestic
  "Egyptian Premier League":     league(233),
  "South African Premier League":league(288),

  // Basketball (logos not on football CDN — use fallback)
  "NBA":                         "",
  "EuroLeague":                  "",
  "NCAA Basketball":             "",
  "WNBA":                        "",
  "Spanish ACB":                 "",

  // Tennis (no CDN logos — use fallback)
  "Wimbledon":                   "",
  "Australian Open":             "",
  "French Open":                 "",
  "US Open":                     "",
  "ATP Masters 1000":            "",
  "WTA Finals":                  "",
};

/* ── Team logos ──────────────────────────────────────────── */
export const TEAM_LOGOS: Record<string, string> = {

  // ── Premier League ───────────────────────────────────────
  "Manchester City":       team(50),
  "Arsenal":               team(42),
  "Liverpool":             team(40),
  "Chelsea":               team(49),
  "Manchester United":     team(33),
  "Tottenham":             team(47),
  "Tottenham Hotspur":     team(47),
  "Newcastle":             team(34),
  "Newcastle United":      team(34),
  "Aston Villa":           team(66),
  "Brighton":              team(51),
  "Brighton & Hove Albion":team(51),
  "West Ham":              team(48),
  "West Ham United":       team(48),
  "Brentford":             team(55),
  "Fulham":                team(36),
  "Crystal Palace":        team(52),
  "Wolves":                team(39),
  "Wolverhampton":         team(39),
  "Everton":               team(45),
  "Nottm Forest":          team(65),
  "Nottingham Forest":     team(65),
  "Bournemouth":           team(35),
  "Sheffield United":      team(62),
  "Burnley":               team(44),
  "Luton Town":            team(71),
  "Leicester":             team(46),
  "Leicester City":        team(46),
  "Ipswich":               team(57),
  "Ipswich Town":          team(57),
  "Southampton":           team(41),
  "Leeds United":          team(63),
  "Watford":               team(38),
  "Norwich City":          team(71),
  "Swansea City":          team(72),
  "Middlesbrough":         team(73),

  // ── La Liga ──────────────────────────────────────────────
  "Real Madrid":           team(541),
  "Barcelona":             team(529),
  "Atletico Madrid":       team(530),
  "Atlético Madrid":       team(530),
  "Sevilla":               team(536),
  "Real Sociedad":         team(548),
  "Villarreal":            team(533),
  "Athletic Club":         team(531),
  "Athletic Bilbao":       team(531),
  "Real Betis":            team(543),
  "Girona":                team(547),
  "Las Palmas":            team(534),
  "Getafe":                team(546),
  "Rayo Vallecano":        team(728),
  "Mallorca":              team(538),
  "Osasuna":               team(727),
  "Valencia":              team(532),
  "Celta Vigo":            team(542),
  "Alaves":                team(540),
  "Espanyol":              team(539),
  "Granada":               team(715),
  "Almeria":               team(717),
  "Cadiz":                 team(724),
  "Valladolid":            team(720),

  // ── Serie A ──────────────────────────────────────────────
  "Inter Milan":           team(505),
  "AC Milan":              team(489),
  "Juventus":              team(496),
  "Napoli":                team(492),
  "Roma":                  team(497),
  "Lazio":                 team(487),
  "Atalanta":              team(499),
  "Fiorentina":            team(502),
  "Torino":                team(503),
  "Bologna":               team(500),
  "Monza":                 team(511),
  "Udinese":               team(494),
  "Sassuolo":              team(490),
  "Lecce":                 team(867),
  "Hellas Verona":         team(504),
  "Empoli":                team(508),
  "Cagliari":              team(488),
  "Genoa":                 team(495),
  "Frosinone":             team(512),
  "Salernitana":           team(514),
  "Como":                  team(507),
  "Venezia":               team(517),
  "Parma":                 team(498),

  // ── Bundesliga ───────────────────────────────────────────
  "Bayern Munich":         team(157),
  "Borussia Dortmund":     team(165),
  "Bayer Leverkusen":      team(168),
  "RB Leipzig":            team(173),
  "Eintracht Frankfurt":   team(169),
  "Wolfsburg":             team(161),
  "Union Berlin":          team(182),
  "Freiburg":              team(160),
  "Borussia Monchengladbach": team(163),
  "Borussia Mönchengladbach": team(163),
  "Cologne":               team(167),
  "FC Köln":               team(167),
  "Werder Bremen":         team(162),
  "Mainz":                 team(164),
  "Hoffenheim":            team(176),
  "Stuttgart":             team(172),
  "Augsburg":              team(170),
  "Bochum":                team(175),
  "Heidenheim":            team(3469),
  "Darmstadt":             team(3462),
  "Hamburg":               team(178),
  "Schalke":               team(174),
  "Hertha Berlin":         team(180),

  // ── Ligue 1 ──────────────────────────────────────────────
  "PSG":                   team(85),
  "Paris Saint-Germain":   team(85),
  "Monaco":                team(91),
  "AS Monaco":             team(91),
  "Nice":                  team(84),
  "OGC Nice":              team(84),
  "Lyon":                  team(80),
  "Olympique Lyonnais":    team(80),
  "Marseille":             team(81),
  "Olympique Marseille":   team(81),
  "Lille":                 team(79),
  "Lens":                  team(116),
  "RC Lens":               team(116),
  "Rennes":                team(93),
  "Strasbourg":            team(95),
  "Montpellier":           team(89),
  "Nantes":                team(83),
  "Lorient":               team(112),
  "Reims":                 team(92),
  "Toulouse":              team(96),
  "Le Havre":              team(108),
  "Clermont":              team(522),
  "Brest":                 team(97),
  "Metz":                  team(87),
  "Auxerre":               team(86),
  "Angers":                team(82),

  // ── Championship ─────────────────────────────────────────
  "Sunderland":            team(69),
  "West Brom":             team(60),
  "West Bromwich Albion":  team(60),
  "Millwall":              team(64),
  "QPR":                   team(68),
  "Preston":               team(74),
  "Coventry":              team(75),
  "Stoke City":            team(70),
  "Cardiff":               team(72),
  "Blackburn":             team(73),

  // ── Champions League extras ───────────────────────────────
  "Porto":                 team(212),
  "Benfica":               team(211),
  "Ajax":                  team(194),
  "PSV":                   team(197),
  "Feyenoord":             team(196),
  "Celtic":                team(31),
  "Rangers":               team(39),
  "Shakhtar Donetsk":      team(294),
  "Dynamo Kyiv":           team(293),
  "Red Bull Salzburg":     team(322),
  "Braga":                 team(228),
  "Sporting CP":           team(228),
  "Sporting Lisbon":       team(228),
  "Club Brugge":           team(258),
  "Anderlecht":            team(257),
  "Galatasaray":           team(357),
  "Fenerbahce":            team(356),
  "Besiktas":              team(355),
  "PAOK":                  team(396),
  "Olympiakos":            team(398),
  "Dinamo Zagreb":         team(358),
  "Red Star Belgrade":     team(389),
  "Young Boys":            team(327),
  "Basel":                 team(325),
  "Slavia Prague":         team(373),
  "Viktoria Plzen":        team(374),
  "Sparta Prague":         team(372),

  // ── CAF Champions League ─────────────────────────────────
  "Al Ahly":               team(1900),
  "Zamalek":               team(1899),
  "Wydad Casablanca":      team(2899),
  "Espérance ST":          team(1901),
  "Espérance de Tunis":    team(1901),
  "Mamelodi Sundowns":     team(1903),
  "TP Mazembe":            team(3303),
  "RS Berkane":            team(5558),
  "CR Belouizdad":         team(2837),
  "USM Alger":             team(2834),
  "MC Alger":              team(2835),
  "Simba SC":              team(6361),
  "Young Africans":        team(6359),
  "Pyramids FC":           team(2883),
  "Petro de Luanda":       team(4773),
  "ASEC Mimosas":          team(5015),
  "Stade d'Abidjan":       team(5017),
  "Kaizer Chiefs":         team(1904),
  "Orlando Pirates":       team(1905),
  "Zamalek SC":            team(1899),

  // ── Egyptian Premier League ───────────────────────────────
  "Zamalek SC":            team(1899),
  "El Masry":              team(1907),
  "Ismaily":               team(1908),
  "Smouha":                team(1910),
  "ENPPI":                 team(1911),

  // ── South African Premier League ─────────────────────────
  "Kaizer Chiefs":         team(1904),
  "Orlando Pirates":       team(1905),
  "Sundowns":              team(1903),
  "SuperSport United":     team(1906),
  "Cape Town City":        team(5563),
  "AmaZulu":               team(5562),

  // ── World Cup national teams ──────────────────────────────
  "Brazil":                team(6),
  "France":                team(2),
  "Argentina":             team(26),
  "England":               team(10),
  "Germany":               team(25),
  "Spain":                 team(9),
  "Portugal":              team(27),
  "Netherlands":           team(1),
  "Italy":                 team(768),
  "Belgium":               team(1),
  "Croatia":               team(3),
  "Morocco":               team(31),
  "Senegal":               team(33),
  "Nigeria":               team(27),
  "Egypt":                 team(26),
  "Cameroon":              team(25),
  "Ghana":                 team(24),
  "Ivory Coast":           team(32),
  "South Africa":          team(37),
  "Algeria":               team(20),
  "Tunisia":               team(29),
  "Japan":                 team(15),
  "South Korea":           team(17),
  "Australia":             team(13),
  "USA":                   team(11),
  "Mexico":                team(16),
  "Uruguay":               team(7),
  "Colombia":              team(5),
  "Chile":                 team(4),

  // ── Europa League ────────────────────────────────────────
  "Galatasaray":           team(357),
  "Villarreal":            team(533),
  "Olympiakos":            team(398),
  "Fenerbahce":            team(356),
};

/** Resolve a team name to its logo URL, or empty string if unknown */
export function getTeamLogo(name: string): string {
  return TEAM_LOGOS[name] ?? "";
}

/** Resolve a league/competition name to its logo URL, or empty string */
export function getLeagueLogo(name: string): string {
  return LEAGUE_LOGOS[name] ?? "";
}
