version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: betfuz-api
          ContainerPort: 3000
        PlatformVersion: LATEST
        NetworkConfiguration:
          AwsvpcConfiguration:
            Subnets:
              - subnet-xxxxx # Replace with your subnet IDs
              - subnet-yyyyy
            SecurityGroups:
              - sg-xxxxx # Replace with your security group ID
            AssignPublicIp: ENABLED

Hooks:
  - BeforeInstall: 'BeforeInstall'
  - AfterInstall: 'AfterInstall'
  - AfterAllowTestTraffic: 'AfterAllowTestTraffic'
  - BeforeAllowTraffic: 'BeforeAllowTraffic'
  - AfterAllowTraffic: 'AfterAllowTraffic'
