/* ── CDN base: set VITE_LOGO_CDN_BASE in .env.production to use S3.
       When unset, falls back to the original third-party CDNs.       ── */
const CDN = (import.meta.env.VITE_LOGO_CDN_BASE as string | undefined)?.replace(/\/$/, "");

/* Football teams/leagues — API-Sports IDs */
const F   = (id: number) => CDN
  ? `${CDN}/football/teams/${id}.png`
  : `https://media.api-sports.io/football/teams/${id}.png`;

const FL  = (id: number) => CDN
  ? `${CDN}/football/leagues/${id}.png`
  : `https://media.api-sports.io/football/leagues/${id}.png`;

/* NBA official SVGs */
const NBA = (id: number) => CDN
  ? `${CDN}/basketball/nba/${id}.svg`
  : `https://cdn.nba.com/logos/nba/${id}/global/L/logo.svg`;

/* TheSportsDB team/league images (CC BY 4.0) */
export const TSDB_TEAM  = (id: number, asset = "badge.png") =>
  CDN ? `${CDN}/tsdb/teams/${id}/${asset}` : `https://www.thesportsdb.com/images/media/team/badge/${id}.png`;
export const TSDB_LEAGUE = (id: number, asset = "badge.png") =>
  CDN ? `${CDN}/tsdb/leagues/${id}/${asset}` : `https://www.thesportsdb.com/images/media/league/badge/${id}.png`;

/* US sports leagues (ESPN public CDN / S3 mirror) */
const NFL = (abbr: string) => CDN ? `${CDN}/nfl/teams/${abbr}.png`
  : `https://a.espncdn.com/i/teamlogos/nfl/500/${abbr}.png`;
const MLB_T = (abbr: string) => CDN ? `${CDN}/mlb/teams/${abbr}.png`
  : `https://a.espncdn.com/i/teamlogos/mlb/500/${abbr}.png`;
const NHL_T = (abbr: string) => CDN ? `${CDN}/nhl/teams/${abbr}.png`
  : `https://a.espncdn.com/i/teamlogos/nhl/500/${abbr}.png`;

/* Country flags (Twemoji MIT, mirrored to S3) */
export const FLAG = (iso: string) => CDN ? `${CDN}/flags/${iso.toLowerCase()}.svg`
  : `https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/svg/${
      iso.toLowerCase().split("").map(c => (0x1F1E6 + c.charCodeAt(0) - 97).toString(16)).join("-")
    }.svg`;

/* ── League logos ─────────────────────────────────────────── */
export const LEAGUE_LOGOS: Record<string, string> = {
  /* ── Football ─────────────────────────────────────────────── */
  "Premier League":               FL(39),
  "English Premier League":       FL(39),
  "Champions League":             FL(2),
  "UEFA Champions League":        FL(2),
  "Europa League":                FL(3),
  "UEFA Europa League":           FL(3),
  "Conference League":            FL(848),
  "La Liga":                      FL(140),
  "Bundesliga":                   FL(78),
  "Serie A":                      FL(135),
  "Ligue 1":                      FL(61),
  "Championship":                 FL(40),
  "Scottish Premiership":         FL(179),
  "Eredivisie":                   FL(88),
  "Belgian Pro League":           FL(144),
  "Primeira Liga":                FL(94),
  "Süper Lig":                    FL(203),
  "Super Lig":                    FL(203),
  "MLS":                          FL(253),
  "Liga MX":                      FL(262),
  "Argentine Primera":            FL(128),
  "Brazilian Série A":            FL(71),
  "Russian Premier League":       FL(235),
  "Saudi Pro League":             FL(307),
  "Chinese Super League":         FL(169),
  "J1 League":                    FL(98),
  "K League":                     FL(292),
  "Indian Super League":          FL(323),
  "A-League":                     FL(188),
  "Egyptian Premier League":      FL(233),
  "South African Premier League": FL(288),
  "Moroccan Botola":              FL(200),
  "Tunisian Ligue 1":             FL(204),
  "Algerian Ligue 1":             FL(186),
  "Nigerian NPFL":                FL(866),
  "Ghanaian Premier League":      FL(789),
  "U17 World Cup":                FL(19),
  "U20 World Cup":                FL(18),
  "CAF Champions League":         FL(12),
  "African Cup of Nations":       FL(6),
  "World Cup":                    FL(1),
  "Copa América":                 FL(9),
  "CONCACAF Champions":           FL(26),
  "Copa Libertadores":            FL(11),
  /* ── Basketball ─────────────────────────────────────────────── */
  "NBA":           CDN ? `${CDN}/basketball/nba-league.png` : "https://a.espncdn.com/i/teamlogos/leagues/500/nba.png",
  "WNBA":          CDN ? `${CDN}/basketball/leagues/13.png` : "https://media.api-sports.io/basketball/leagues/13.png",
  "EuroLeague":    CDN ? `${CDN}/basketball/leagues/120.png` : "https://media.api-sports.io/basketball/leagues/120.png",
  "Spanish ACB":   CDN ? `${CDN}/basketball/leagues/119.png` : "https://media.api-sports.io/basketball/leagues/119.png",
  /* ── US Sports ─────────────────────────────────────────────── */
  "NFL":  CDN ? `${CDN}/nfl/league.png`  : "https://a.espncdn.com/i/teamlogos/leagues/500/nfl.png",
  "MLB":  CDN ? `${CDN}/mlb/league.png`  : "https://a.espncdn.com/i/teamlogos/leagues/500/mlb.png",
  "NHL":  CDN ? `${CDN}/nhl/league.png`  : "https://a.espncdn.com/i/teamlogos/leagues/500/nhl.png",
  /* ── Cricket ───────────────────────────────────────────────── */
  "IPL":    TSDB_LEAGUE(4403),
  "BBL":    TSDB_LEAGUE(4404),
  "CPL":    TSDB_LEAGUE(4405),
  /* ── Rugby ─────────────────────────────────────────────────── */
  "Premiership Rugby": TSDB_LEAGUE(4409),
  "Top 14":            TSDB_LEAGUE(4410),
  "Super Rugby":       TSDB_LEAGUE(4411),
  "NRL":               TSDB_LEAGUE(4412),
  "Super League":      TSDB_LEAGUE(4413),
  /* ── MMA ────────────────────────────────────────────────────── */
  "UFC": CDN ? `${CDN}/mma/ufc.png` : "https://a.espncdn.com/i/teamlogos/leagues/500/ufc.png",
  /* ── Tennis ─────────────────────────────────────────────────── */
  "ATP": CDN ? `${CDN}/tennis/atp.png` : "https://a.espncdn.com/i/teamlogos/leagues/500/atp.png",
  "WTA": CDN ? `${CDN}/tennis/wta.png` : "https://a.espncdn.com/i/teamlogos/leagues/500/wta.png",
};

export const TEAM_LOGOS: Record<string, string> = {

  /* ── Premier League ───────────────────────────────────── */
  "Arsenal":              F(42),
  "Aston Villa":          F(66),
  "Bournemouth":          F(35),
  "Brentford":            F(55),
  "Brighton":             F(51),
  "Brighton & Hove Albion": F(51),
  "Chelsea":              F(49),
  "Crystal Palace":       F(52),
  "Everton":              F(45),
  "Fulham":               F(36),
  "Ipswich Town":         F(57),
  "Leicester City":       F(46),
  "Liverpool":            F(40),
  "Manchester City":      F(50),
  "Manchester United":    F(33),
  "Newcastle United":     F(34),
  "Nottingham Forest":    F(65),
  "Southampton":          F(41),
  "Tottenham":            F(47),
  "Tottenham Hotspur":    F(47),
  "West Ham":             F(48),
  "West Ham United":      F(48),
  "Wolves":               F(39),
  "Wolverhampton":        F(39),

  /* ── La Liga ──────────────────────────────────────────── */
  "Real Madrid":          F(541),
  "Barcelona":            F(529),
  "Atlético Madrid":      F(530),
  "Atletico Madrid":      F(530),
  "Sevilla":              F(536),
  "Real Betis":           F(543),
  "Valencia":             F(532),
  "Athletic Club":        F(531),
  "Athletic Bilbao":      F(531),
  "Villarreal":           F(533),
  "Real Sociedad":        F(548),
  "Osasuna":              F(727),
  "Girona":               F(547),
  "Celta Vigo":           F(538),
  "Rayo Vallecano":       F(728),
  "Espanyol":             F(534),
  "Getafe":               F(546),
  "Las Palmas":           F(875),
  "Alaves":               F(542),
  "Leganes":              F(723),
  "Mallorca":             F(722),
  "Valladolid":           F(720),

  /* ── Bundesliga ───────────────────────────────────────── */
  "Bayern Munich":        F(157),
  "Borussia Dortmund":    F(165),
  "RB Leipzig":           F(173),
  "Bayer Leverkusen":     F(168),
  "Eintracht Frankfurt":  F(169),
  "Borussia Mönchengladbach": F(163),
  "Wolfsburg":            F(161),
  "Freiburg":             F(160),
  "Hoffenheim":           F(167),
  "Stuttgart":            F(172),
  "Werder Bremen":        F(162),
  "Union Berlin":         F(182),
  "Mainz":                F(164),
  "Augsburg":             F(170),
  "Heidenheim":           F(703),
  "Bochum":               F(176),
  "St. Pauli":            F(186),
  "Holstein Kiel":        F(185),

  /* ── Serie A ──────────────────────────────────────────── */
  "Juventus":             F(496),
  "Inter Milan":          F(505),
  "AC Milan":             F(489),
  "Milan":                F(489),
  "Napoli":               F(492),
  "Roma":                 F(497),
  "Lazio":                F(487),
  "Atalanta":             F(499),
  "Fiorentina":           F(502),
  "Torino":               F(503),
  "Bologna":              F(500),
  "Udinese":              F(494),
  "Cagliari":             F(490),
  "Genoa":                F(495),
  "Verona":               F(504),
  "Parma":                F(715),
  "Monza":                F(867),
  "Lecce":                F(867),
  "Empoli":               F(511),
  "Como":                 F(717),

  /* ── Ligue 1 ──────────────────────────────────────────── */
  "PSG":                  F(85),
  "Paris Saint-Germain":  F(85),
  "Lyon":                 F(80),
  "Marseille":            F(81),
  "Monaco":               F(91),
  "Lille":                F(79),
  "Nice":                 F(84),
  "Lens":                 F(116),
  "Rennes":               F(94),
  "Strasbourg":           F(95),
  "Reims":                F(93),
  "Montpellier":          F(82),
  "Toulouse":             F(96),
  "Nantes":               F(83),
  "Auxerre":              F(78),
  "Le Havre":             F(1073),
  "Brest":                F(113),
  "Saint-Étienne":        F(97),
  "Angers":               F(112),
  "Stade de Reims":       F(93),

  /* ── EFL Championship ─────────────────────────────────── */
  "Leeds United":         F(63),
  "Burnley":              F(44),
  "Sheffield United":     F(62),
  "Sheffield Wednesday":  F(74),
  "Sheffield Wednesday FC": F(74),
  "Middlesbrough":        F(70),
  "Watford":              F(38),
  "Sunderland":           F(746),
  "Coventry City":        F(1346),
  "Coventry":             F(1346),
  "Hull City":            F(64),
  "Norwich City":         F(71),
  "Millwall":             F(58),
  "Bristol City":         F(56),
  "West Brom":            F(60),
  "West Bromwich Albion": F(60),
  "QPR":                  F(72),
  "Queens Park Rangers":  F(72),
  "Stoke City":           F(75),
  "Blackburn Rovers":     F(67),
  "Blackburn":            F(67),
  "Oxford United":        F(1338),
  "Derby County":         F(69),
  "Derby":                F(69),
  "Luton Town":           F(1359),
  "Luton":                F(1359),
  "Swansea City":         F(76),
  "Swansea":              F(76),
  "Preston North End":    F(59),
  "Preston":              F(59),
  "Portsmouth":           F(1355),
  "Cardiff City":         F(43),
  "Cardiff":              F(43),
  "Plymouth Argyle":      F(1357),
  "Plymouth":             F(1357),
  /* ── EFL League One ──────────────────────────────────── */
  "Birmingham City":      F(54),
  "Birmingham City FC":   F(54),
  "Birmingham":           F(54),
  "Charlton Athletic":    F(1335),
  "Charlton Athletic FC": F(1335),
  "Charlton":             F(1335),
  /* ── LaLiga extras ───────────────────────────────────── */
  "Elche CF":             F(797),
  "Elche":                F(797),

  /* ── UEFA Champions League extras ───────────────────────── */
  "Porto":                F(212),
  "Ajax":                 F(194),
  "Braga":                F(228),
  "Galatasaray":          F(357),
  "Rangers":              F(39),   // note: Rangers use 399
  "Celtic":               F(396),
  "Benfica":              F(211),
  "Sporting CP":          F(228),
  "PSV":                  F(197),
  "Feyenoord":            F(193),
  "Shakhtar Donetsk":     F(480),
  "Red Bull Salzburg":    F(409),
  "Club Brugge":          F(399),
  "Anderlecht":           F(403),
  "Dortmund":             F(165),

  /* ── Europa League extras ─────────────────────────────── */
  "Eintracht":            F(169),
  "Marseille ":           F(81),
  "Bayer Leverkusen ":    F(168),

  /* ── CAF Champions League ─────────────────────────────── */
  "Al Ahly":              F(10),
  "Zamalek":              F(87),
  "Zamalek SC":           F(87),
  "Wydad Casablanca":     F(95),
  "Espérance ST":         F(91),
  "Mamelodi Sundowns":    F(648),
  "TP Mazembe":           F(98),
  "CR Belouizdad":        F(680),
  "USM Alger":            F(681),
  "MC Alger":             F(687),
  "RS Berkane":           F(2277),
  "Pyramids FC":          F(2278),

  /* ── NFL ──────────────────────────────────────────────── */
  "Arizona Cardinals":      NFL("ari"),
  "Atlanta Falcons":        NFL("atl"),
  "Baltimore Ravens":       NFL("bal"),
  "Buffalo Bills":          NFL("buf"),
  "Carolina Panthers":      NFL("car"),
  "Chicago Bears":          NFL("chi"),
  "Cincinnati Bengals":     NFL("cin"),
  "Cleveland Browns":       NFL("cle"),
  "Dallas Cowboys":         NFL("dal"),
  "Denver Broncos":         NFL("den"),
  "Detroit Lions":          NFL("det"),
  "Green Bay Packers":      NFL("gb"),
  "Houston Texans":         NFL("hou"),
  "Indianapolis Colts":     NFL("ind"),
  "Jacksonville Jaguars":   NFL("jax"),
  "Kansas City Chiefs":     NFL("kc"),
  "Los Angeles Chargers":   NFL("lac"),
  "Los Angeles Rams":       NFL("lar"),
  "Las Vegas Raiders":      NFL("lv"),
  "Miami Dolphins":         NFL("mia"),
  "Minnesota Vikings":      NFL("min"),
  "New England Patriots":   NFL("ne"),
  "New Orleans Saints":     NFL("no"),
  "New York Giants":        NFL("nyg"),
  "New York Jets":          NFL("nyj"),
  "Philadelphia Eagles":    NFL("phi"),
  "Pittsburgh Steelers":    NFL("pit"),
  "Seattle Seahawks":       NFL("sea"),
  "San Francisco 49ers":    NFL("sf"),
  "Tampa Bay Buccaneers":   NFL("tb"),
  "Tennessee Titans":       NFL("ten"),
  "Washington Commanders":  NFL("wsh"),

  /* ── MLB ──────────────────────────────────────────────── */
  "Arizona Diamondbacks":   MLB_T("ari"),
  "Atlanta Braves":         MLB_T("atl"),
  "Baltimore Orioles":      MLB_T("bal"),
  "Boston Red Sox":         MLB_T("bos"),
  "Chicago Cubs":           MLB_T("chc"),
  "Chicago White Sox":      MLB_T("chw"),
  "Cincinnati Reds":        MLB_T("cin"),
  "Cleveland Guardians":    MLB_T("cle"),
  "Colorado Rockies":       MLB_T("col"),
  "Detroit Tigers":         MLB_T("det"),
  "Houston Astros":         MLB_T("hou"),
  "Kansas City Royals":     MLB_T("kc"),
  "Los Angeles Angels":     MLB_T("laa"),
  "Los Angeles Dodgers":    MLB_T("lad"),
  "Miami Marlins":          MLB_T("mia"),
  "Milwaukee Brewers":      MLB_T("mil"),
  "Minnesota Twins":        MLB_T("min"),
  "New York Mets":          MLB_T("nym"),
  "New York Yankees":       MLB_T("nyy"),
  "Oakland Athletics":      MLB_T("oak"),
  "Philadelphia Phillies":  MLB_T("phi"),
  "Pittsburgh Pirates":     MLB_T("pit"),
  "San Diego Padres":       MLB_T("sd"),
  "Seattle Mariners":       MLB_T("sea"),
  "San Francisco Giants":   MLB_T("sf"),
  "St. Louis Cardinals":    MLB_T("stl"),
  "Tampa Bay Rays":         MLB_T("tb"),
  "Texas Rangers":          MLB_T("tex"),
  "Toronto Blue Jays":      MLB_T("tor"),
  "Washington Nationals":   MLB_T("wsh"),

  /* ── NHL ──────────────────────────────────────────────── */
  "Anaheim Ducks":          NHL_T("ana"),
  "Boston Bruins":          NHL_T("bos"),
  "Buffalo Sabres":         NHL_T("buf"),
  "Calgary Flames":         NHL_T("cgy"),
  "Carolina Hurricanes":    NHL_T("car"),
  "Chicago Blackhawks":     NHL_T("chi"),
  "Colorado Avalanche":     NHL_T("col"),
  "Columbus Blue Jackets":  NHL_T("cbj"),
  "Dallas Stars":           NHL_T("dal"),
  "Detroit Red Wings":      NHL_T("det"),
  "Edmonton Oilers":        NHL_T("edm"),
  "Florida Panthers":       NHL_T("fla"),
  "Los Angeles Kings":      NHL_T("lak"),
  "Minnesota Wild":         NHL_T("min"),
  "Montreal Canadiens":     NHL_T("mtl"),
  "Nashville Predators":    NHL_T("nsh"),
  "New Jersey Devils":      NHL_T("njd"),
  "New York Islanders":     NHL_T("nyi"),
  "New York Rangers":       NHL_T("nyr"),
  "Ottawa Senators":        NHL_T("ott"),
  "Philadelphia Flyers":    NHL_T("phi"),
  "Pittsburgh Penguins":    NHL_T("pit"),
  "San Jose Sharks":        NHL_T("sjs"),
  "Seattle Kraken":         NHL_T("sea"),
  "St. Louis Blues":        NHL_T("stl"),
  "Tampa Bay Lightning":    NHL_T("tbl"),
  "Toronto Maple Leafs":    NHL_T("tor"),
  "Vancouver Canucks":      NHL_T("van"),
  "Vegas Golden Knights":   NHL_T("vgk"),
  "Washington Capitals":    NHL_T("wsh"),
  "Winnipeg Jets":          NHL_T("wpg"),

  /* ── NBA (NBA.com CDN) ────────────────────────────────── */
  "Atlanta Hawks":            NBA(1610612737),
  "Boston Celtics":           NBA(1610612738),
  "Brooklyn Nets":            NBA(1610612751),
  "Charlotte Hornets":        NBA(1610612766),
  "Chicago Bulls":            NBA(1610612741),
  "Cleveland Cavaliers":      NBA(1610612739),
  "Dallas Mavericks":         NBA(1610612742),
  "Denver Nuggets":           NBA(1610612743),
  "Detroit Pistons":          NBA(1610612765),
  "Golden State Warriors":    NBA(1610612744),
  "Houston Rockets":          NBA(1610612745),
  "Indiana Pacers":           NBA(1610612754),
  "Los Angeles Clippers":     NBA(1610612746),
  "LA Clippers":              NBA(1610612746),
  "Los Angeles Lakers":       NBA(1610612747),
  "LA Lakers":                NBA(1610612747),
  "Memphis Grizzlies":        NBA(1610612763),
  "Miami Heat":               NBA(1610612748),
  "Milwaukee Bucks":          NBA(1610612749),
  "Minnesota Timberwolves":   NBA(1610612750),
  "New Orleans Pelicans":     NBA(1610612740),
  "New York Knicks":          NBA(1610612752),
  "Oklahoma City Thunder":    NBA(1610612760),
  "Orlando Magic":            NBA(1610612753),
  "Philadelphia 76ers":       NBA(1610612755),
  "Phoenix Suns":             NBA(1610612756),
  "Portland Trail Blazers":   NBA(1610612757),
  "Sacramento Kings":         NBA(1610612758),
  "San Antonio Spurs":        NBA(1610612759),
  "Toronto Raptors":          NBA(1610612761),
  "Utah Jazz":                NBA(1610612762),
  "Washington Wizards":       NBA(1610612764),
};
